# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadAndInstallpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 557)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: white\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 61))
        self.label.setStyleSheet("QLabel{\n"
"background-image: url(:/newPrefix/win11.png);\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/win11.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color : rgb(47, 47, 212) \n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 510, 141, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    background-image: url(:/newPrefix/microsoft.png);\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/microsoft.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(190, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButtonQuit = QtWidgets.QPushButton(Dialog)
        self.pushButtonQuit.setGeometry(QtCore.QRect(580, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60, 96, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.labelDownloading = QtWidgets.QLabel(Dialog)
        self.labelDownloading.setGeometry(QtCore.QRect(40, 110, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelDownloading.setFont(font)
        self.labelDownloading.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.labelDownloading.setObjectName("labelDownloading")
        self.labelInstalling = QtWidgets.QLabel(Dialog)
        self.labelInstalling.setGeometry(QtCore.QRect(40, 160, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelInstalling.setFont(font)
        self.labelInstalling.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.labelInstalling.setObjectName("labelInstalling")
        self.progressBarDownload = QtWidgets.QProgressBar(Dialog)
        self.progressBarDownload.setGeometry(QtCore.QRect(270, 122, 251, 31))
        self.progressBarDownload.setStyleSheet("QProgressBar{\n"
"    color: black\n"
"}")
        self.progressBarDownload.setProperty("value", 0)
        self.progressBarDownload.setObjectName("progressBarDownload")
        self.progressBarInstall = QtWidgets.QProgressBar(Dialog)
        self.progressBarInstall.setGeometry(QtCore.QRect(270, 160, 251, 41))
        self.progressBarInstall.setStyleSheet("QProgressBar{\n"
"    color: black\n"
"}")
        self.progressBarInstall.setProperty("value", 0)
        self.progressBarInstall.setObjectName("progressBarInstall")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Windows 11"))
        self.label_4.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.aka.ms/support\">Support</a>"))
        self.label_5.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.microsoft/en-us/legal\">Legal</a>"))
        self.pushButtonQuit.setText(_translate("Dialog", "Quit"))
        self.labelDownloading.setText(_translate("Dialog", "Downloading Windows 11"))
        self.labelInstalling.setText(_translate("Dialog", "Installing Windows 11"))

