# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initialMessagePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 557)
        Dialog.setStyleSheet("QDialog{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 61))
        self.label.setStyleSheet("QLabel{\n"
"    background-image: url(:/newPrefix/win11.png);\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/win11.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(32)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color : rgb(47, 47, 212) \n"
"}")
        self.label_2.setObjectName("label_2")
        self.labelInitialMessageTitle = QtWidgets.QLabel(Dialog)
        self.labelInitialMessageTitle.setGeometry(QtCore.QRect(40, 120, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        font.setItalic(False)
        self.labelInitialMessageTitle.setFont(font)
        self.labelInitialMessageTitle.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.labelInitialMessageTitle.setText("")
        self.labelInitialMessageTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInitialMessageTitle.setWordWrap(True)
        self.labelInitialMessageTitle.setObjectName("labelInitialMessageTitle")
        self.pushButtonInitialNext = QtWidgets.QPushButton(Dialog)
        self.pushButtonInitialNext.setGeometry(QtCore.QRect(580, 510, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(13)
        self.pushButtonInitialNext.setFont(font)
        self.pushButtonInitialNext.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60,96,255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonInitialNext.setObjectName("pushButtonInitialNext")
        self.labelInitialMessage = QtWidgets.QLabel(Dialog)
        self.labelInitialMessage.setGeometry(QtCore.QRect(40, 200, 621, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.labelInitialMessage.setFont(font)
        self.labelInitialMessage.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.labelInitialMessage.setText("")
        self.labelInitialMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInitialMessage.setWordWrap(True)
        self.labelInitialMessage.setObjectName("labelInitialMessage")
        self.pushButtonQuit = QtWidgets.QPushButton(Dialog)
        self.pushButtonQuit.setGeometry(QtCore.QRect(470, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60, 96, 255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 507, 141, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    background-image: url(:/newPrefix/microsoft.png);\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/microsoft.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(190, 510, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 500, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Windows 11"))
        self.pushButtonInitialNext.setText(_translate("Dialog", "Next"))
        self.pushButtonQuit.setText(_translate("Dialog", "Quit"))
        self.label_4.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.aka.ms/support\">Support</a>"))
        self.label_5.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.microsoft/en-us/legal\">Legal</a>"))

