# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'licenceActivation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 557)
        Dialog.setStyleSheet("QDialog{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 61))
        self.label.setStyleSheet("QLabel{\n"
"    background-image: url(:/newPrefix/win11.png);\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/win11.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(64, 64, 255)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color:black\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEditCode1 = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode1.setGeometry(QtCore.QRect(30, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCode1.setFont(font)
        self.lineEditCode1.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(249, 255, 179);\n"
"    color: black;\n"
"    border-radius: 0px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}")
        self.lineEditCode1.setText("")
        self.lineEditCode1.setObjectName("lineEditCode1")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(96, 170, 16, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEditCode2 = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode2.setGeometry(QtCore.QRect(120, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCode2.setFont(font)
        self.lineEditCode2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(249, 255, 179);\n"
"    color: black;\n"
"    border-radius: 0px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}")
        self.lineEditCode2.setObjectName("lineEditCode2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(190, 167, 20, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEditCode3 = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode3.setGeometry(QtCore.QRect(210, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCode3.setFont(font)
        self.lineEditCode3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(249, 255, 179);\n"
"    color: black;\n"
"    border-radius: 0px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}")
        self.lineEditCode3.setObjectName("lineEditCode3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(280, 160, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    color:black\n"
"}")
        self.label_6.setObjectName("label_6")
        self.lineEditCode4 = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode4.setGeometry(QtCore.QRect(300, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCode4.setFont(font)
        self.lineEditCode4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(249, 255, 179);\n"
"    color: black;\n"
"    border-radius: 0px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}")
        self.lineEditCode4.setObjectName("lineEditCode4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(370, 160, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    color:black\n"
"}")
        self.label_7.setObjectName("label_7")
        self.lineEditCode5 = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode5.setGeometry(QtCore.QRect(390, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCode5.setFont(font)
        self.lineEditCode5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(249, 255, 179);\n"
"    color: black;\n"
"    border-radius: 0px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(94, 79, 255)\n"
"}")
        self.lineEditCode5.setObjectName("lineEditCode5")
        self.pushButtonNext = QtWidgets.QPushButton(Dialog)
        self.pushButtonNext.setGeometry(QtCore.QRect(583, 509, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonNext.setFont(font)
        self.pushButtonNext.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60,96,255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonQuit = QtWidgets.QPushButton(Dialog)
        self.pushButtonQuit.setGeometry(QtCore.QRect(473, 509, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60,96,255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 510, 141, 31))
        self.label_8.setStyleSheet("QLabel{\n"
"    \n"
"    background-image: url(:/newPrefix/microsoft.png);\n"
"}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/microsoft.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(190, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(270, 510, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.labelIncorrectCode = QtWidgets.QLabel(Dialog)
        self.labelIncorrectCode.setGeometry(QtCore.QRect(30, 240, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelIncorrectCode.setFont(font)
        self.labelIncorrectCode.setStyleSheet("QLabel{\n"
"    color:red\n"
"}")
        self.labelIncorrectCode.setText("")
        self.labelIncorrectCode.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIncorrectCode.setObjectName("labelIncorrectCode")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Windows 11"))
        self.label_3.setText(_translate("Dialog", "Please enter the licence key to activate your product. "))
        self.label_4.setText(_translate("Dialog", "-"))
        self.label_5.setText(_translate("Dialog", "-"))
        self.label_6.setText(_translate("Dialog", "-"))
        self.label_7.setText(_translate("Dialog", "-"))
        self.pushButtonNext.setText(_translate("Dialog", "Next"))
        self.pushButtonQuit.setText(_translate("Dialog", "Quit"))
        self.label_9.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.aka.ms/support\">Support</a>"))
        self.label_10.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.microsoft/en-us/legal\">Legal</a>"))
