# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectInstallationType.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 557)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(255,255,255)\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 61))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    background-image: url(:/newPrefix/win11.png);\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/win11.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color:rgb(64, 64, 255)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: black\n"
"}")
        self.label_3.setObjectName("label_3")
        self.radioButtonKeepFiles = QtWidgets.QRadioButton(Dialog)
        self.radioButtonKeepFiles.setGeometry(QtCore.QRect(40, 170, 281, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonKeepFiles.setFont(font)
        self.radioButtonKeepFiles.setStyleSheet("QRadioButton{\n"
"    color: black\n"
"}")
        self.radioButtonKeepFiles.setObjectName("radioButtonKeepFiles")
        self.radioButtonReinstall = QtWidgets.QRadioButton(Dialog)
        self.radioButtonReinstall.setGeometry(QtCore.QRect(40, 200, 361, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonReinstall.setFont(font)
        self.radioButtonReinstall.setStyleSheet("QRadioButton{\n"
"    color: black\n"
"}")
        self.radioButtonReinstall.setObjectName("radioButtonReinstall")
        self.pushButtonNext = QtWidgets.QPushButton(Dialog)
        self.pushButtonNext.setGeometry(QtCore.QRect(583, 509, 91, 31))
        self.pushButtonNext.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 254, 226);\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    border: 1px dotted rgb(60,96,255)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(60, 96, 255)\n"
"}")
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 500, 141, 31))
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    background-image: url(:/newPrefix/microsoft.png);\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/microsoft.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(180, 500, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(260, 500, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Windows 11"))
        self.label_3.setText(_translate("Dialog", "Select installation type"))
        self.radioButtonKeepFiles.setText(_translate("Dialog", "Keep personal files and folders"))
        self.radioButtonReinstall.setText(_translate("Dialog", "Delete Everything (Reinstall Windows)"))
        self.pushButtonNext.setText(_translate("Dialog", "Continue"))
        self.label_5.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.aka.ms/support\">Support</a>"))
        self.label_6.setText(_translate("Dialog", "<a style=\"color:black; text-decoration:none\" href=\"https://www.microsoft/en-us/legal\">Legal</a>"))

